# frozen_string_literal: true

source 'https://rubygems.org' do
  gem 'kitchen-terraform', '~> 5.0'
  gem 'inspec', '= 4.18.51' # See https://github.com/newcontext-oss/kitchen-terraform/issues/384
  gem 'inspec-core', '= 4.18.51'

  group 'development' do
#    gem 'inspec-core-bin', '= 4.18.51' # Kitchen-TF sometimes swallows Inspec errors
  end
end
